// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQhbpE6PQ9mHZ_sdm34iYeKRCWUPx_QE',
    appId: '1:267969186164:web:400a002819309947dcc421',
    messagingSenderId: '267969186164',
    projectId: 'reallygood-ec680',
    authDomain: 'reallygood-ec680.firebaseapp.com',
    storageBucket: 'reallygood-ec680.appspot.com',
    measurementId: 'G-9FT24H24ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGgTIzteAhvlRIkV5r6oBwfb2DFnnbC9o',
    appId: '1:267969186164:android:0892ea12d812619fdcc421',
    messagingSenderId: '267969186164',
    projectId: 'reallygood-ec680',
    storageBucket: 'reallygood-ec680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN09GwLjRq9sT6d33M-YIVaDqDDOLeuaw',
    appId: '1:267969186164:ios:b7fd21454eba69d5dcc421',
    messagingSenderId: '267969186164',
    projectId: 'reallygood-ec680',
    storageBucket: 'reallygood-ec680.appspot.com',
    iosClientId: '267969186164-0a8od09vg4bv2g972a4dc6ae9h08fmkn.apps.googleusercontent.com',
    iosBundleId: 'com.reallygood.mobileClient',
  );
}
