# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Build

on: workflow_dispatch 

jobs:
  buildandroid:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'
          channel: 'stable'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build apk
      - name: Upload build apk --debug
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-debug
          path: build/app/outputs/apk/debug/app-debug.apk
      - run: flutter build apk --release
      - name: Upload build apk
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-release
          path: build/app/outputs/apk/release/app-release.apk
  buildios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'
          channel: 'stable'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build ios --no-codesign
      - name: Upload build ipa
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa-debug
          path: build/ios/iphoneos/Runner.app
      - run: flutter build ios --release --no-codesign
      - name: Upload build ipa
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa-release
          path: build/ios/iphoneos/Runner.app
